### ISSUE TITLE
Getting 400 error with payment request.

### ISSUE THREAD

**Issue by joshuaiz** [SK8-PTY-LTD/wc-rest-payment#1]
Hello,

Thanks for this plugin! Trying it out with a headless WP + React front end.

Testing in Postman, I've formatted my request with the body and an existing order id but getting this error:

```json
{
    "code": 400,
    "message": "Payment Method 'payment_method' is required.",
    "data": {
        "status": 400
    }
}
```

Here is my request endpoint:

`https://viz.local/wp-json/wc/v2/payment`

And the body:
```json
{
	"payment_method": "stripe",
	"order_id": "62",
	"payment_token":"tok_mastercard"
}
```

See attached screenshot:
<img width="563" alt="screen shot 2018-08-06 at 4 08 07 pm" src="https://user-images.githubusercontent.com/1096738/43741432-ebfa256e-9993-11e8-9df8-8ab8a2b1897b.png">

What am I missing here? Thanks!

**Comment by jacktator** [comment]
In your header, set content to text-json.

In your screenshot (Postman), 'Body' 'raw' and next to it, instead of 'Text', it should be 'JSON'

**Comment by joshuaiz** [comment]
Brilliant...that works. Thanks!
