### ISSUE TITLE
Return WooCommerce Order Notes on failed payment

### ISSUE THREAD

**Issue by joshuaiz** [SK8-PTY-LTD/wc-rest-payment#4]
Thanks again for this plugin - it has been working great for me.

This is just a feature request: I'm using Stripe and if a payment fails, it would be great to return the actual error message from Stripe to present to the customer. This message gets added to the Order Notes of the order so it should be easy to return.

Here is the relevant code from `class-wc-rest-payment-public`:

```javascript
switch ($payment_method) {
case "stripe":
    $wc_gateway_stripe = new WC_Gateway_Stripe();
    $_POST['stripe_token'] = $payment_token;
    $payment_result = $wc_gateway_stripe->process_payment($order_id);
    if ($payment_result['result'] === "success") {
        $response['code'] = 200;
        $response['message'] = __("Your Payment was Successful", "wc-rest-payment");
    } else {
        $response['code'] = 411;
        $response['message'] = __("Please enter valid card details", "wc-rest-payment");
    }
    break;
    //...
```

For example, when testing with Stripe using the expired card test numbers, the Order Notes for the order show 'The card has expired.' This would be much more informative to the customer.

I *could* set up an additional api request to grab the Order Notes on a failed order but I think the plugin could do this internally.

Thanks!

**Comment by jacktator** [comment]
@joshuaiz Hi, thank you for the suggestion. I think it's a great idea, and I did a bit digging.

Here's the relevant functions in WooCommerce Stripe module, 
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L847

This plugin gets the info returned by WooCommerce Stripe module, and since the module is not returning the error detail in the error object, we can't do much.

`catch ( WC_Stripe_Exception $e ) {
			wc_add_notice( $e->getLocalizedMessage(), 'error' );
			WC_Stripe_Logger::log( 'Error: ' . $e->getMessage() );
			do_action( 'wc_gateway_stripe_process_payment_error', $e, $order );
			/* translators: error message */
			**$order->update_status( 'failed' );
			return array(
				'result'   => 'fail',
				'redirect' => '',
			);**
		}`

Do you have any suggestion?}

**Comment by joshuaiz** [comment]
@jacktator Ahhh got it - yeah that makes it tough.

What I ended up doing was making another WP REST API call if the order fails and then grabbing the latest Order Note and updating the app state 'status' with that.

I have a headless WP setup with a React front end so here's kind of a condensed version of my `Checkout.js` if it may help anyone else:

I'm using React hooks so I have some state:

```javascript
const Checkout = ({ cart, removeFromCart, clearCart }) => {
    const [order, setOrder] = useState()
    const [orderComplete, setOrderComplete] = useState(false)
    const [orderError, setOrderError] = useState()
    const [status, setStatus] = useState()
    const [pending, setPending] = useState(false)
```

Then later in my function component here is my `paymentSubmit()` function:

```javascript
const paymentSubmit = ({ order_id, token }) => {
    let paymentData = JSON.stringify({
        payment_method: 'stripe',
        order_id: order_id,
        payment_token: token
    })

    axios
        .post(
            `${params.liveUrl}/wp-json/wc/v2/payment?consumer_key=${
                process.env.REACT_APP_WC_CONSUMER_KEY
            }&consumer_secret=${process.env.REACT_APP_WC_CONSUMER_SECRET}`,
            paymentData,
            axiosConfig
        )
        .then(response => {
            console.log('Payment Submit', response.data)
            if (response.data.code === 200) {
                setOrder(response.data)
                setOrderComplete(true)
                setPending(false)
                clearCart()
            } else {
                getNotes(order_id)
            }
        })
        .catch(err => {
            console.log('AXIOS ERROR payment Submit: ', err)
            setOrderError(err)
        })
}
```
Which sends the `order_id` to the `getNotes()` function to update the status:

```javascript
const getNotes = order_id => {
    axios
        .get(
            `${
                params.liveUrl
            }/wp-json/wc/v3/orders/${order_id}/notes?consumer_key=${
                process.env.REACT_APP_WC_CONSUMER_KEY
            }&consumer_secret=${process.env.REACT_APP_WC_CONSUMER_SECRET}`
        )
        .then(response => {
            setStatus(response.data[0].note)
            setPending(false)
        })
}
```

The `response.data[0].note` is the key here as the latest note (in this case the error) will be the first Order Note in the array so we can grab that and use it. In my case, I'm displaying that to the customer:

![screen shot 2019-01-12 at 6 31 21 pm](https://user-images.githubusercontent.com/1096738/51079969-55b0c900-1698-11e9-821b-b7a6d8c44bed.png)

^^^ 'The card has expired' was the Order Note in WooCommerce returned from Stripe. I was using a test CC number for expired cards. You can find all of the test Stripe CC numbers [here](https://stripe.com/docs/testing#cards). I've tested with different errors like invalid CVC code, etc. and it returns different messages to the Order Note so this is working.

![screen shot 2019-01-12 at 6 31 33 pm](https://user-images.githubusercontent.com/1096738/51079976-9577b080-1698-11e9-9083-95977e501f48.png)

^^^ And you can see here the returned message from the plugin but having more detailed info at least helps the customer figure out what went wrong.

This is all using Stripe so I don't know about other payment processors but hopefully this can help someone else.

**Comment by jacktator** [comment]
@joshuaiz 

Thank you for the thorough detail! 

I'll close the issue for now.
